# Data Science
# Exercise 4 - Collaborative Filtering
<br/>Student:
<br/>se21m024
<br/>Thomas Stummer
<br/><br/>The interpretation of the data can be found in the document <b><i>se21m024_Stummer_ex4_Coll_Filtering.pdf</i></b>.
<br/><br/>
The library 'Surprise' (https://surprise.readthedocs.io/en/stable/index.html) was used to create the following results. The code is highly inspired by the example code provided by the libries official documentation.
<br/><br/>
The data set was provided by<br>
F. Maxwell Harper and Joseph A. Konstan. 2015. The MovieLens Datasets:
History and Context. ACM Transactions on Interactive Intelligent
Systems (TiiS) 5, 4, Article 19 (December 2015), 19 pages.
DOI=http://dx.doi.org/10.1145/2827872
<br/><br/>

# Import necessary dependencies

In [1]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate
from surprise import KNNWithMeans
import datetime

# import pandas as pd
# import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D
# import matplotlib as mpl
# import numpy as np
# import seaborn as sns
# import math as math
# import itertools as it
# from sklearn.manifold import MDS
# import sklearn.datasets as dt
# from sklearn.metrics.pairwise import manhattan_distances, euclidean_distances
# from matplotlib.offsetbox import OffsetImage, AnnotationBbox
# from sklearn import cluster, datasets, mixture
# from sklearn.neighbors import kneighbors_graph
# from sklearn.preprocessing import StandardScaler
# from itertools import cycle, islice
# import matplotlib.pyplot as plt
# from sklearn import cluster, datasets, mixture
# from sklearn.neighbors import kneighbors_graph
# from sklearn.preprocessing import StandardScaler
# from itertools import cycle, islice
# from sklearn.preprocessing import OneHotEncoder
# from surprise import SVD
# from surprise import Dataset
# from surprise.model_selection import cross_validate

# pd.options.display.max_columns = None

# %matplotlib inline

## Import Data

In [11]:
# Load 100k data
reader = Reader(line_format='user item rating timestamp', sep='\t')
data_100k = Dataset.load_from_file('./Data/ml-100k/u.data', reader=reader)

# Load 1m data
reader = Reader(line_format='user item rating timestamp', sep='::')
data_1m = Dataset.load_from_file('./Data/ml-1m/ratings.dat', reader=reader)

In [12]:
## Define algorithms
def generate_predictions(data, user_based):

    # Create 5 random training and test sets
    # Student ID: se21m024 -> random_state = 21024
    train_test_sets = [train_test_split(data, test_size=.2, random_state=21024)]

    for i in range(4):
        train_test_sets.append(train_test_split(data, test_size=.2))

    # Configure the algorithm
    k = 40
    min_k = 1
    algorithm_options = {'name': 'cosine', 'user_based': user_based}
    algorithm = KNNWithMeans(k, min_k, algorithm_options)

    # Train the algorithm and test the accuracy
    results = []
    for train_set, test_set in train_test_sets:
        start_time = datetime.datetime.now()
        algorithm.fit(train_set)
        predictions = algorithm.test(test_set)
        end_time = datetime.datetime.now()
        mse = accuracy.mse(predictions)
        runtime_sec = (end_time - start_time).total_seconds()
        results.append([mse, runtime_sec])

    # Print results
    print('\nResults')
    for mse, runtime_sec in results:
        print('MSE: ' + str(mse), 'Runtime: ' + str(runtime_sec) + ' seconds')

# Generate and evaluate predictions

## 100k data set

### User Based Filtering

In [13]:
print('\n### 100k User based ###')
generate_predictions(data_100k, True)



### 100k User based ###
Computing the cosine similarity matrix...
Done computing similarity matrix.
MSE: 0.9048
Computing the cosine similarity matrix...
Done computing similarity matrix.
MSE: 0.9134
Computing the cosine similarity matrix...
Done computing similarity matrix.
MSE: 0.9204
Computing the cosine similarity matrix...
Done computing similarity matrix.
MSE: 0.9136
Computing the cosine similarity matrix...
Done computing similarity matrix.
MSE: 0.9211

Results
MSE: 0.9047969682388375 , Runtime: 4.505119 seconds
MSE: 0.9133843010099434 , Runtime: 4.465996 seconds
MSE: 0.9204352970435222 , Runtime: 4.398881 seconds
MSE: 0.9135552977943385 , Runtime: 4.426656 seconds
MSE: 0.9211383454964173 , Runtime: 4.560298 seconds


### Item Based Filtering

In [ ]:
print('\n### 100k Item based ###')
generate_predictions(data_100k, False)

## 1m data set

### User Based Filtering

In [14]:
print('\n### 1m User based ###')
generate_predictions(data_1m, True)


### 1m User based ###
Computing the cosine similarity matrix...
Done computing similarity matrix.


KeyboardInterrupt: 

### Item Based Filtering

In [ ]:
print('\n### 1m Item based ###')
generate_predictions(data_1m, False)

## Algorithm 1: User-User Similarity matrix
Using Cosine similarity


In [40]:
# Source code taken from: https://github.com/pratiknabriya/Recommender-System-Collaborative-Filtering-MovieLens/blob/main/collaborative_filtering_movielense.ipynb

from sklearn.metrics.pairwise import cosine_similarity

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_data)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)
print(user_similarity.shape)

# Predicting the User ratings on the movies
user_predicted_ratings = np.dot(user_similarity, user_data)
user_predicted_ratings

# np.multiply for cell-by-cell multiplication 

user_final_ratings = np.multiply(user_predicted_ratings, dummy_train)
user_final_ratings.head()


[[1.         0.12749131 0.04335795 ... 0.06502325 0.13515049 0.37295319]
 [0.12749131 1.         0.06767143 ... 0.14257081 0.16123985 0.12237756]
 [0.04335795 0.06767143 1.         ... 0.0841076  0.09209121 0.        ]
 ...
 [0.06502325 0.14257081 0.0841076  ... 1.         0.03385171 0.03615073]
 [0.13515049 0.16123985 0.09209121 ... 0.03385171 1.         0.1711502 ]
 [0.37295319 0.12237756 0.         ... 0.03615073 0.1711502  1.        ]]
(943, 943)
movieId        1          2          3           4          5          6     \
userId                                                                        
1          0.000000   0.000000   0.000000  194.097860  70.514738  16.172180   
2          0.000000  42.010575  43.549925   78.795848  31.690498  11.821509   
3        100.995218  20.508668  19.362439   34.759775  17.216300   4.888464   
4        111.438109  23.360723  19.908019   41.802880  17.347856   4.326971   
5          0.000000  94.897344  57.068788  154.025809  58.206840  10.27

### Top 5 movie recommendations for the User 42



In [21]:
user_final_ratings.iloc[42].sort_values(ascending = False)[0:5]

movieId
1      382.819959
56     346.559374
318    310.153532
168    306.110967
210    295.614854
Name: 43, dtype: float64

## Algorithm 2: Item-based collaborative filtering


In [22]:
movie_features = X_train.pivot(index = 'movieId', columns = 'userId', values = 'rating').fillna(0)
movie_features.head()


userId   1    2    3    4    5    6    7    8    9    10   11   12   13   14   \
movieId                                                                         
1        5.0  4.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  3.0  0.0   
2        3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0   
3        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  5.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

userId   15   16   17   18   19   20   21   22   23   24   25   26   27   28   \
movieId                                                                         
1        1.0  0.0  4.0  0.0  0.0  3.0  5.0  0.0  5.0  0.0  5.0  3.0  0.0  0.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  5.0  0.0  3.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   29   30   31   32   33   34   35   36   37   38   39   40   41   42   \
movieId                                                                         
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  5.0   
2        0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   43   44   45   46   47   48   49   50   51   52   53   54   55   56   \
movieId                                                                         
1        0.0  4.0  5.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  4.0  0.0  4.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        2.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        4.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5        4.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   57   58   59   60   61   62   63   64   65   66   67   68   69   70   \
movieId                                                                         
1        5.0  5.0  2.0  0.0  0.0  2.0  3.0  4.0  3.0  0.0  3.0  0.0  0.0  0.0   
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   
3        0.0  0.0  4.0  0.0  0.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   71   72   73   74   75   76   77   78   79   80   81   82   83   84   \
movieId                                                                         
1        0.0  4.0  2.0  0.0  4.0  0.0  5.0  0.0  4.0  0.0  4.0  0.0  0.0  0.0   
2        0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  2.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   85   86   87   88   89   90   91   92   93   94   95   96   97   98   \
movieId                                                                         
1        0.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  5.0  4.0  5.0  5.0  4.0  0.0   
2        0.0  0.0  4.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  2.0  0.0  0.0  0.0   
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
4        0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId   99   100  101  

## Item-Item Similarity matrix
Using Cosine similarity


In [23]:
from sklearn.metrics.pairwise import cosine_similarity

# Item Similarity Matrix using Cosine similarity as a similarity measure between Items
item_similarity = cosine_similarity(movie_features)
item_similarity[np.isnan(item_similarity)] = 0
print(item_similarity)
print("- "*10)
print(item_similarity.shape)

# Predicting the User ratings on the movies

item_predicted_ratings = np.dot(movie_features.T, item_similarity)
item_predicted_ratings


# Filtering the ratings only for the movies not already rated by the user for recommendation
# np.multiply for cell-by-cell multiplication 

item_final_ratings = np.multiply(item_predicted_ratings, dummy_train)
item_final_ratings.head()




[[1.         0.31697113 0.28767995 ... 0.         0.         0.05201389]
 [0.31697113 1.         0.18691343 ... 0.         0.08789381 0.        ]
 [0.28767995 0.18691343 1.         ... 0.         0.         0.10289915]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.08789381 0.         ... 0.         1.         0.        ]
 [0.05201389 0.         0.10289915 ... 0.         0.         1.        ]]
- - - - - - - - - - 
(1643, 1643)


movieId       1           2          3           4           5          6     \
userId                                                                         
1         0.000000    0.000000   0.000000  246.716873  152.817539  62.259473   
2         0.000000   31.008898  32.337738   39.798814   27.085758  16.540623   
3        19.322631   13.382176  13.184284   15.634446   12.248506   5.761955   
4        14.907988   10.113397   9.316696   12.287974    8.466436   3.973269   
5         0.000000  118.433222  78.581603  131.718756   84.575315  22.731378   

movieId        7           8          9          10          11          12    \
userId                                                                          
1          0.000000    0.000000   0.000000   0.000000    0.000000    0.000000   
2         50.232915   40.843374  49.213948   0.000000   43.071606   47.361342   
3         20.716287   15.630575  16.707699  11.517513   20.852231   20.935561   
4         14.268868   11.956146  11.747551   6.677790    0.000000   14.843779   
5        119.657756  119.883998  94.392940  61.295967  119.683990  123.718106   

movieId       13         14          15         16          17         18    \
userId                                                                        
1         0.000000   0.000000  180.356926   0.000000  163.334288   0.000000   
2         0.000000  38.739857   47.874517  24.595817   26.269351  11.299381   
3        15.435925  10.391790   15.695113   8.603261   14.663748   4.631932   
4        10.422646   7.622988   11.445923   4.826701    9.160910   2.354148   
5        88.905264  58.902876   93.015051  39.607698    0.000000  24.944686   

movieId       19         20         21          22         23         24    \
userId                                                                       
1         0.000000   0.000000   0.000000    0.000000   0.000000   0.000000   
2         0.000000  31.899636  26.744906   44.527243  35.151856  35.606622   
3         8.127559  11.164783  11.324379   19.218021  14.823464  15.737568   
4         5.453762   6.765061   8.240998   14.305041  10.804096  10.676743   
5        33.214975  43.965223   0.000000  135.613559  98.992635   0.000000   

movieId       25         26         27          28          29         30    \
userId                                                                        
1         0.000000   0.000000   0.000000    0.000000  186.956273   0.000000   
2        48.871019  28.684689  21.304517   41.701461   27.807366  18.716158   
3        15.925270  11.906111  10.821385   16.027104   13.246225   5.844547   
4        11.496541   8.021564   7.858547   12.096603    9.190926   4.129810   
5         0.000000  67.474928  73.296682  136.555532    0.000000  51.750432   

movieId        31         32          33         34         35         36    \
userId                                                                        
1        218.895385   0.000000    0.000000   0.000000   0.000000  69.899203   
2         36.328464  27.018935   28.484934   9.803898   5.637446  14.217608   
3         15.782384  11.675963   13.848021   6.558817   2.744222   7.622855   
4         11.517287   7.537007    9.869051   2.808213   2.331357   4.931937   
5        115.991450  73.171748  105.461840  30.839092  26.262989  37.129020   

movieId       37          38         39         40         41         42    \
userId                                                                       
1        51.764115    0.000000   0.000000   0.000000   0.000000   0.000000   
2         6.715238   30.968196  26.199656  21.530797  17.707096  32.564050   
3         4.161270   14.231165  11.707454   8.632675   9.111118  13.015377   
4         2.578153   10.267830   8.498025   5.797285   6.914930   9.388591   
5        31.712499  108.956626  86.635403   0.000000  72.797574   0.000000   

movieId       43         44         45         46          47         48    \
userId                               

### Top 5 movie recommendations for the User 42

In [24]:
item_final_ratings.iloc[42].sort_values(ascending = False)[0:5]

movieId
210    213.758875
423    212.735547
168    210.741268
56     208.795315
195    204.752782
Name: 43, dtype: float64

# Evaluation

Source code taken from: https://github.com/pratiknabriya/Recommender-System-Collaborative-Filtering-MovieLens/blob/main/collaborative_filtering_movielense.ipynb

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the User instead of predicting it for the movie not rated by the user.


## Using User-User similarity

In [54]:
test_user_features = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)
test_user_similarity = cosine_similarity(test_user_features)
test_user_similarity[np.isnan(test_user_similarity)] = 0

#print(test_user_similarity)
#print("- "*10)
#print(test_user_similarity.shape)

user_predicted_ratings_test = np.dot(test_user_similarity, test_user_features)
user_predicted_ratings_test

#print(user_predicted_ratings_test)
#print(dummy_test)



# Testing on the movies already rated by the user
test_user_final_rating = np.multiply(user_predicted_ratings_test, dummy_test)
#print(test_user_final_rating)


# We need to normalize the final rating values between range (0.5, 5)
from sklearn.preprocessing import MinMaxScaler

X = test_user_final_rating.copy() 



#X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

#print(X)

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

#print(pred)

# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

test = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)
#print(test)

# RMSE Score -> todo: change to MSE

from sklearn.metrics import mean_squared_error

#print(test.shape)
#print(pred.shape)

mse = mean_squared_error(test, pred)
print(mse)



0.26029562467251444


## Using Item-Item Similarity

In [ ]:


test_item_features = X_test.pivot(index = 'movieId', columns = 'userId', values = 'rating').fillna(0)
test_item_similarity = cosine_similarity(test_item_features)
test_item_similarity[np.isnan(test_item_similarity)] = 0 

print(test_item_similarity)
print("- "*10)
print(test_item_similarity.shape)

item_predicted_ratings_test = np.dot(test_item_features.T, test_item_similarity )
item_predicted_ratings_test

test_item_final_rating = np.multiply(item_predicted_ratings_test, dummy_test)
test_item_final_rating.head()

ratings['rating'].describe()

# But we need to normalize the final rating values between range (0.5, 5)

from sklearn.preprocessing import MinMaxScaler

X = test_item_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

test = X_test.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)
test.head()


# MSE
mse = mean_squared_error(test, pred)
print(mse)






[[1.         0.11198089 0.11115644 ... 0.         0.08014439 0.08014439]
 [0.11198089 1.         0.1039166  ... 0.         0.         0.        ]
 [0.11115644 0.1039166  1.         ... 0.         0.         0.18090681]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.08014439 0.         0.         ... 0.         1.         0.        ]
 [0.08014439 0.         0.18090681 ... 0.         0.         1.        ]]
- - - - - - - - - - 
(1499, 1499)
[[3.35005351        nan 2.59624443 ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]
2.022128341828588
